### ISSUE TITLE
HCP_1200 t1w 原始数据

### ISSUE THREAD

**Issue by hongtao-gg** [iwuqing/ArSSR#11]
作者您好，我用您发的脚本下载的HCP_1200 t1w的图像数据，尺寸大小为（260，311，260），并不是您论文里尺寸为（320320256）您可以再提供一下HCP-1200 T1W的原始数据的网盘链接吗（之前的过期了）。第二个问题是，您是如何讲图片裁剪到264264264的？万分感谢您可以抽空回答我。邮箱：[454191383@qq.com](mailto:454191383@qq.com)

**Comment by iwuqing** [comment]
你好，你可以从以下百度网盘链接下载~
链接：https://pan.baidu.com/s/1ivy8TXUIO2nW35XK2ThafA 
提取码：8m67
