### ISSUE TITLE
Which HCP-1200 data set of skull dissection was used in the paper?

### ISSUE THREAD

**Issue by Homiltons** [iwuqing/ArSSR#13]
I am running HCP datasets for the first time and do not know which is the dataset described in this article.

**Comment by iwuqing** [comment]
Hi~ @TOGOTOO 
Sorry for the delay in my response. The HCP dataset we used is the T1W HCP dataset. And the dataset is skull-stripped. You can download the raw dataset from Baidu Netdisk.

link: https://pan.baidu.com/s/1ivy8TXUIO2nW35XK2ThafA
password:8m67
