### ISSUE TITLE
自动分割的问题

### ISSUE THREAD

**Issue by NewboySoCool** [iwuqing/ArSSR#7]
你好，这是我得到的 GT：996782的分割图。感觉跟你论文里的差距还挺大。
我用这段代码获取的 segmentation.nii.gz， `segmentation_dict = antspynet.utilities.deep_atropos(image, do_preprocessing=True)`
分割网络推理时需要的模板图像用的是它自己下载的， `brainExtractionRobustT1.h5，croppedMni152.nii.gz，croppedMni152Priors.nii.gz ， S_template3.nii.gz， sixTissueOctantBrainSegmentationWithPriors1.h5`， 这里这些模板图像需要更改吗？
<img width="847" alt="自己的分割结果" src="https://github.com/iwuqing/ArSSR/assets/93995539/18a7c52a-8065-404f-9c4a-ae77dfa4d77a">

**Comment by iwuqing** [comment]
我们使用的是他自带的模板。你这个结果确实感觉差距有点大。我想是不是这个参数do_preprocessing=True要设置为false？因为这个代码太久了，我也记不太清了。

**Comment by NewboySoCool** [comment]
好的，我在多尝试下。 我这个是用cpu跑出来的结果，你们当时用gpu了吗？感谢！Ma在 2023年6月14日，上午7:52，Qing Wu ***@***.***> 写道：﻿
我们使用的是他自带的模板。你这个结果确实感觉差距有点大。我想是不是这个参数do_preprocessing=True要设置为false？因为这个代码太久了，我也记不太清了。

**Comment by iwuqing** [comment]
应该是用了GPU。但我记得分割速度确实不是特别快，应该是因为3D的问题。

**Comment by NewboySoCool** [comment]
> 应该是用了GPU。但我记得分割速度确实不是特别快，应该是因为3D的问题。

大哥，我没弄出来，难受！能帮忙找下你们之前用的代码吗？

**Comment by iwuqing** [comment]
> 

我找找啊，因为时间实在太久了，而且这个代码也不是主要的代码。所以真不一定能找到了。

**Comment by iwuqing** [comment]
> > 应该是用了GPU。但我记得分割速度确实不是特别快，应该是因为3D的问题。
> 
> 大哥，我没弄出来，难受！能帮忙找下你们之前用的代码吗？

顺便你可以说下你现在是有啥问题吗？

**Comment by NewboySoCool** [comment]
> > > 应该是用了GPU。但我记得分割速度确实不是特别快，应该是因为3D的问题。
> > 
> > 
> > 大哥，我没弄出来，难受！能帮忙找下你们之前用的代码吗？
> 
> 顺便你可以说下你现在是有啥问题吗？

找不找到都太感谢了，太感谢了，目前最好的分割效果还是我上面那个图，我尝试了do_preprocessing=True改成False更不对，我在github问了ANTsPyNet的大佬，让我尝试用没去颅骨的数据试下，后来我tensorlfow环境出问题了就没测试成。我又尝试了其他的自动分割的方法，HighRes3DNet，我试了下在unprocessed 的HCP数据上还可以分割得感觉正常，但在processed的HCP数据上就分割不对，几乎就自动分割不出来。

**Comment by NewboySoCool** [comment]
> > > 应该是用了GPU。但我记得分割速度确实不是特别快，应该是因为3D的问题。
> > 
> > 
> > 大哥，我没弄出来，难受！能帮忙找下你们之前用的代码吗？
> 
> 顺便你可以说下你现在是有啥问题吗？

师兄，能找到嘛？之前环境就突然不行了，现在咋装都不对，给我人装麻了

**Comment by iwuqing** [comment]
不好意思，我这几天在忙一个会议的返稿。所以最近没啥时间，如果你很急的话可以参考下这篇文章是怎样做分割的。他们也做了一样的分割评估：https://arxiv.org/pdf/2205.11346.pdf

**Comment by NewboySoCool** [comment]
> 不好意思，我这几天在忙一个会议的返稿。所以最近没啥时间，如果你很急的话可以参考下这篇文章是怎样做分割的。他们也做了一样的分割评估：https://arxiv.org/pdf/2205.11346.pdf

好，师兄，你最近先忙，有时间找就行，我也不着急，就是弄不出来难受。我在找找其他的分割的方法看看能不能用，感谢！

**Comment by NewboySoCool** [comment]
> 不好意思，我这几天在忙一个会议的返稿。所以最近没啥时间，如果你很急的话可以参考下这篇文章是怎样做分割的。他们也做了一样的分割评估：https://arxiv.org/pdf/2205.11346.pdf

你好，实在不好意思，又打扰你了，我最近重新装了Antspynet的GPU版本，也可以用了，我用没有skull-stripped的HCP 1200 data做出来好像是对的
![results_with_skull-stripped](https://github.com/iwuqing/ArSSR/assets/93995539/b63a3cd2-96f1-4923-9f86-e70f67bee57c)

但是，我将 `antspynet.utilities.deep_atropos(image, do_preprocessing=False, verbose=True)` `do_preprocessing=False`改成了False，用GPU跑出来的结果，在形状上是对上了，但出现了新的问题，我很郁闷。下图所示：

![分割结果不用 d0_processed=False](https://github.com/iwuqing/ArSSR/assets/93995539/0a2f9892-eb49-4f38-bcbc-3730dbd83259)

**Comment by NewboySoCool** [comment]
你好，我找到了解决方法，并尝试做出来了结果。太感谢之前你的回复了！
![image](https://github.com/iwuqing/ArSSR/assets/93995539/df91b6de-076e-488d-ac1b-60d1a7d41fbc)

**Comment by iwuqing** [comment]
> 你好，我找到了解决方法，并尝试做出来了结果。太感谢之前你的回复了！ ![image](https://user-images.githubusercontent.com/93995539/258703707-df91b6de-076e-488d-ac1b-60d1a7d41fbc.png)

恭喜你哦！祝你一切顺利

**Comment by NewboySoCool** [comment]
> > 你好，我找到了解决方法，并尝试做出来了结果。太感谢之前你的回复了！ ![image](https://user-images.githubusercontent.com/93995539/258703707-df91b6de-076e-488d-ac1b-60d1a7d41fbc.png)
> 
> 恭喜你哦！祝你一切顺利

太感谢你了，同样祝你一切顺利！

**Comment by hongtao-gg** [comment]
> 你好，我找到了解决方法，并尝试做出来了结果。太感谢之前你的回复了！ ![image](https://user-images.githubusercontent.com/93995539/258703707-df91b6de-076e-488d-ac1b-60d1a7d41fbc.png)

大佬 可以请教一下这个自动分割是怎么做到的吗

**Comment by NewboySoCool** [comment]
把那个Antspy的库里面这个 预处理的几个选项修改下就可以













在 2023-11-08 11:49:28，"hongtao-gg" ***@***.***> 写道：

你好，我找到了解决方法，并尝试做出来了结果。太感谢之前你的回复了！

大佬 可以请教一下这个自动分割是怎么做到的吗
