### ISSUE TITLE
training loss

### ISSUE THREAD

**Issue by chenjiachengzzz** [iwuqing/ArSSR#9]
尊敬的作者您好，你们做出了非常棒的工作，我在复现你们实验结果时，遇到了一个问题，训练 loss 几乎不会变化(一直维持在 0.3)，请问这个现象是正常的吗？希望得到您的解答！

**Comment by iwuqing** [comment]
请问你是在使用哪个数据集进行训练哈?

**Comment by chenjiachengzzz** [comment]
> 请问你是在使用哪个数据集进行训练哈?

使用的是您提供的处理过的 HCP 数据

**Comment by iwuqing** [comment]
请问你在训练的时候都是使用的默认参数吗？

**Comment by chenjiachengzzz** [comment]
> 请问你在训练的时候都是使用的默认参数吗？

使用的是默认参数

**Comment by iwuqing** [comment]
你能展示下你的训练的loss曲线吗？

**Comment by chenjiachengzzz** [comment]
> 你能展示下你的训练的loss曲线吗？

<img width="2014" alt="image" src="https://github.com/iwuqing/ArSSR/assets/54382260/9d42214a-4b25-42f3-89f8-0c03852b2697">
loss 几乎不收敛

**Comment by iwuqing** [comment]
我之前训练并没出现这样情况，你是否可以尝试下把初始学习率降低一些？

**Comment by chenjiachengzzz** [comment]
> 我之前训练并没出现这样情况，你是否可以尝试下把初始学习率降低一些？
![WX20230725-134717@2x](https://github.com/iwuqing/ArSSR/assets/54382260/4cf9d8ec-f041-4bfe-9f89-fd289d7ccb3a)

我现在使用 5e-5的学习率重新训练一下，您看一下 训练参数是否有错。您可以提供一下您训练的 loss 记录给我做一个参考吗？
十分感谢您的耐心回复！

**Comment by chenjiachengzzz** [comment]
> 我之前训练并没出现这样情况，你是否可以尝试下把初始学习率降低一些？

您好，我学习率下降到 5e-5 loss还是不降哎！

**Comment by NewboySoCool** [comment]
> > 我之前训练并没出现这样情况，你是否可以尝试下把初始学习率降低一些？
> 
> 您好，我学习率下降到 5e-5 loss还是不降哎！

之前我也遇到过，但是我把之前的工程下的 __pycache__ 这个缓存文件删掉，我当时就解决了，不知道你那边这样能不能解决

**Comment by chenjiachengzzz** [comment]
> > > 我之前训练并没出现这样情况，你是否可以尝试下把初始学习率降低一些？
> > 
> > 
> > 您好，我学习率下降到 5e-5 loss还是不降哎！
> 
> 之前我也遇到过，但是我把之前的工程下的 **pycache** 这个缓存文件删掉，我当时就解决了，不知道你那边这样能不能解决

哇，可以了啊，loss 在降低了，太感谢大佬了，我被这个问题困惑很久了！
